### ISSUE TITLE
Command line provided in README.md fails

### ISSUE THREAD

**Issue by jayurbain** [mengf1/PAL#5]
I thought your paper was very interesting, so I decided to look at your code. Unfortunately, I have not been able to get it running. Any advice would be appreciated. See below.

Thanks,
Jay
jay.urbain@gmail.com

The application appears to be confused between tensorflow flags and your application flags.

$ python launcher_ner_bilingual.py --agent "CNNDQN" --episode 10000 --budget 1000 --train "en.train;en.testa;en.testb;en.emb;en.model.saved" --test "de.train;de.testa;de.testb;de.emb;de.model.saved"

Traceback (most recent call last):
  File "launcher_ner_bilingual.py", line 15, in <module>
    FLAGS._parse_flags()
  File "/Applications/anaconda/envs/py3.6tf1.3keras/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/Applications/anaconda/envs/py3.6tf1.3keras/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'agent'

**Comment by mengf1** [comment]
It maybe because the tensorflow version I used was a little old. Please use tensorflow 1.0.0 (pip install tensorflow==1.0.0) to solve the problem "FLAGS._parse_flags()'' instead.
